// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkzpudgicwydsrulzusp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5renB1ZGdpY3d5ZHNydWx6dXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNjI2OTEsImV4cCI6MjA3MDYzODY5MX0.fTT-5HtTmY_dtUxWe_d-y3yLZQ6CIKlSoIp2qz2Xd1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});